server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/posdb?serverTimezone=Asia/Tokyo&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.web: DEBUG
    com.example.pos_backend: DEBUG
