spring:
  datasource:
    url: jdbc:mysql://localhost:3306/posdb?serverTimezone=Asia/Tokyo&useSSL=false
    username: root
    password: root

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
