server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pos_backend?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.web: DEBUG
    com.example.pos_backend: DEBUG

# JWT配置
jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  access-token-expiration: 3600      # Access Token 过期时间（秒）- 1小时
  refresh-token-expiration: 2592000  # Refresh Token 过期时间（秒）- 30天