server:
    port: 8080

spring:
    messages:
        basename: i18n/messages
        encoding: UTF-8
    datasource:
        url: jdbc:mysql://localhost:3306/pos_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root

    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:db/migration

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    data:
        redis:
            host: localhost
            port: 6379

logging:
    level:
        org.springframework.web: DEBUG
        com.example.pos_backend: DEBUG

# Sa-Token 配置
sa-token:
    token-name: pos-token # Token 名称 会自动添加到响应头中 存入cookie中
    timeout: 2592000 # Token 超时时间（秒）- 30天