server:
    port: 8080
spring:
    application.name: pos-merchant
    profiles:
        active: @spring.profiles.active@
    datasource:
        host: @database.host@
        db-name: @database.name@
        url: jdbc:p6spy:mysql://${spring.datasource.host}:3306/${spring.datasource.db-name}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
        username: @database.username@
        password: @database.password@
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    jackson:
        time-zone: UTC
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    data:
        redis:
            host: @redis.host@
            port: @redis.port@

logging:
    level:
        root: info
        p6spy: debug
    file:
        path: ./logs
    logback:
        rollingpolicy:
            max-file-size: 10MB
            max-history: 30
            clean-history-on-start: true

# Sa-Token 配置
sa-token:
    token-name: pos-merchant-token # Token 名称 会自动添加到响应头中 存入cookie中
    timeout: 2592000 # Token 超时时间（秒）- 30天
    is-log: true
# Twilio 配置 支持从环境变量中获取
twilio:
    account-sid: ${TWILIO_ACCOUNT_SID:1111}
    auth-token: ${TWILIO_AUTH_TOKEN:1111}
    from-phone-number: ${TWILIO_FROM:1111}

file:
    tenant-quota: 104857600
    minio-default-bucket: public
    preview-host: ${MINIO_HOST_URL:http://127.0.0.1:9000}
    minio:
        host: ${MINIO_HOST:127.0.0.1:9000}
        port: ${MINIO_PORT:9000}
        secure: ${MINIO_SECURE:false}
        access-key: ${MINIO_ACCESS_KEY:1111}
        secret-key: ${MINIO_SECRET_KEY:1111}
